export const siteConfig = {
  brandName: "Rémy Paridaens | Studiebegeleiding in wetenschappen en geschiedenis",
  shortName: "Rémy Paridaens",
  tagline: "Studiebegeleiding in wetenschappen en geschiedenis",
  address: "Geluwestraat 9, 2600 Berchem (Antwerpen)",
  email: "remy.paridaens@hotmail.be",
  phone: "04 73 47 68 93",
  website: "remyparidaens.be",
  websiteUrl: "https://remyparidaens.be",
  instagramHandle: "remyparidaens.be",
  instagramUrl: "https://www.instagram.com/remyparidaens.be/",
  availability: "Werkdagen, vakanties en weekends",
  businessNumber: "",
  vatNumber: "",
  prices: {
    kennismaking: "Gratis",
    online: "€35",
    fysiek: "€40",
    annulatie: "Kosteloos tot 24 uur op voorhand",
  },
};
